import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'
import { Theme, ThemePanel } from '@radix-ui/themes'

import './globals.css'
import '@radix-ui/themes/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Theme>
        <body className={`${inter.className} bg-gradient-to-r from-purple-400 to-violet-700`}>{children}</body>
        {/* <ThemePanel /> */}
      </Theme>
      <Analytics />
    </html>
  )
}
